spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DATABASE_NAME
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
server:
  error:
    include-message: always
    include-binding-errors: always